require_relative 'config'

begin
  conn = PG.connect user: USERNAME, dbname: DBNAME
  puts 'Connected to: ' + conn.db

  print 'The table would be dropped if exists. Continue? [y, n]: '
  if gets.chomp.downcase == 'y'
    conn.exec "DROP TABLE IF EXISTS users"

    conn.exec "CREATE TABLE users(id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, username VARCHAR(30), password VARCHAR(20))"
    #conn.exec "INSERT INTO users (id, username, password) VALUES (2, 'Corch', '228322')"
    puts 'Table ' + USERS_TABLENAME + ' successfully created'
  end
rescue PG::Error => e
  puts e.message
ensure
  conn.close if conn
end
